language: php

php:
  - 5.6
  - 7.0
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.0
    - php: hhvm

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source

script:
  - ./vendor/bin/parallel-lint --exclude vendor ./
  - ./vendor/bin/phpunit --configuration phpunit.xml
  - ./vendor/bin/phpcs --standard=PSR2 -p --report=full --report-checkstyle=build/logs/checkstyle.xml --ignore=config/rrs src/ tests/

after_script:
  - ./vendor/bin/coveralls -v
